### ISSUE TITLE
Update message gives a broken link

### ISSUE THREAD

**Issue by maxsokolovsky** [thycotic/dsv-cli#89]
When the CLI notifies of an update, it prints a link to the relevant binary. When I follow it, my browser hits a No Such Key page. I suspect it's something to do with the `cli-version.json` file, which the CLI initially fetches. It might have incorrectly constructed links.

**Comment by sheldonhull** [comment]
@maxsokolovsky  what version are you on and how do you update? ( We have a lot of new installation  options including brew install etc)

**Comment by andrii-zakurenyi** [comment]
I'll take this issue

**Comment by maxsokolovsky** [comment]
@sheldonhull, I'm on `1.40.1`. I just use the CLI and get an update notification on each request - I use the link from that notification.

**Comment by sheldonhull** [comment]
See release notes. That issue is fixed now. 

https://github.com/DelineaXPM/dsv-cli/releases

Also try brew install or if on Linux snap install now and you'll get the updates automatically. Readme has a lot of automatic install options now. Snap automatically updates for you to if on Linux FYI. 

Reopen if it still doesn't work after update.

**Comment by sheldonhull** [comment]
@maxsokolovsky the url output is fixed but not released yet.
Recommend brew/scoop/aqua/snap install update in the meantime as it doesn't need this anyway and can automate it. We have curl install/powershell options too on the main page if it's useful.

The s3 download links will be fixed in next version `1.40.3`.

**Comment by maxsokolovsky** [comment]
Awesome, thank you!
